# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatogaryCodeAnalyze' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'ReactiveCocoa', '~> 10.0.0'
  pod 'AsyncDisplayKit', '~> 2.2.1'

  # Pods for CatogaryCodeAnalyze

end
